/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThingsImport } from './routes/things'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ThingsRoute = ThingsImport.update({
  id: '/things',
  path: '/things',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/things': {
      id: '/things'
      path: '/things'
      fullPath: '/things'
      preLoaderRoute: typeof ThingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/things': typeof ThingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/things': typeof ThingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/things': typeof ThingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/things'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/things'
  id: '__root__' | '/' | '/things'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThingsRoute: typeof ThingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThingsRoute: ThingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/things"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/things": {
      "filePath": "things.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
